import { StyleSheet } from "react-native";
import { rem } from "@/theme/units";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  map: {
    flex: 1,
  },
  modalContainer: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "transparent",
  },
  modalContent: {
    backgroundColor: "white",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    height: 300,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  closeButton: {
    padding: 4,
  },
  sportsContainer: {
    marginTop: rem(10),
    flexDirection: "row",
    display: "flex",
    flexWrap: "wrap",
    gap: rem(8),
  },
  sportButton: {
    paddingHorizontal: rem(12),
    paddingVertical: rem(6),
    borderRadius: rem(16),
    backgroundColor: "rgba(213, 208, 169, 0.51)",
  },
  selectedSport: {
    backgroundColor: "#803511",
  },
  sportText: {
    fontWeight: "bold",

    color: "#803511",
  },
  sportsTitle: {
    marginTop: rem(10),
    marginLeft: rem(10),
    fontFamily: "Poppins-Bold",
    fontWeight: "bold",
    color: "#803511",
  },
  selectedSportText: {
    color: "white",
  },
  navigationButton: {
    padding: 4,
  },
  markerInfo: {
    marginTop: 10,
  },
  title: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 10,
  },
  creator: {
    fontSize: 16,
    color: "#666",
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 5,
  },
  sportItem: {
    backgroundColor: "#E8E8E8",
    padding: rem(5),
    borderRadius: rem(5),
    marginRight: rem(5),
    marginBottom: rem(5),
  },
  noSports: {
    color: "#666",
    fontStyle: "italic",
  },
  dates: {
    fontSize: 14,
    color: "#666",
  },
  addButton: {
    zIndex: 10000,
    position: "absolute",
    top: 50,
    right: 10,
    backgroundColor: "white",
    width: 70,
    height: 70,
    borderRadius: 25,
    justifyContent: "center",
    alignItems: "center",
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  MenuButton: {
    zIndex: 10000,
    position: "absolute",
    alignSelf: "center",
    bottom: 10,
    backgroundColor: "white",
    width: 50,
    height: 50,
    borderRadius: 9999,
    justifyContent: "center",
    alignItems: "center",
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },

  menu: {
    position: "absolute",
    zIndex: 1000,
    paddingTop: rem(20),
    bottom: 0,
    left: 0,
    width: "100%",
    height: rem(200),
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    backgroundColor: "#FFFBE4",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  notifications: {
    zIndex: 10000,
    position: "absolute",
    top: 150,
    left: 10,
    backgroundColor: "white",
    width: 70,
    height: 70,
    borderRadius: 25,
    justifyContent: "center",
    alignItems: "center",
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    fontFamily: "Poppins-Bold",
    fontWeight: "bold",
    color: "#803511",
  },
  viewAll: {
    zIndex: 10000,
    position: "absolute",
    top: 50,
    left: 10,
    backgroundColor: "white",
    width: 70,
    height: 70,
    borderRadius: 25,
    justifyContent: "center",
    alignItems: "center",
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    fontFamily: "Poppins-Bold",
    fontWeight: "bold",
    color: "#803511",
  },
  filterControls: {
    padding: rem(16),
    gap: rem(16),
  },
  filterTitle: {
    fontSize: rem(18),
    fontWeight: "bold",
    color: "#803511",
    marginBottom: rem(8),
  },
  filterSection: {
    gap: rem(8),
  },
  filterLabel: {
    fontSize: rem(16),
    color: "#5B3400",
    fontWeight: "500",
  },
  filterOptions: {
    flexDirection: "row",
    gap: rem(8),
  },
  filterButton: {
    paddingHorizontal: rem(12),
    paddingVertical: rem(6),
    borderRadius: rem(16),
    backgroundColor: "rgba(213, 208, 169, 0.51)",
  },
  filterButtonActive: {
    backgroundColor: "#803511",
  },
  filterButtonText: {
    color: "#803511",
    fontWeight: "500",
  },
  filterButtonTextActive: {
    color: "white",
  },
  filterActions: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: rem(8),
    marginTop: rem(8),
  },
  clearButton: {
    flex: 1,
    padding: rem(12),
    borderRadius: rem(16),
    backgroundColor: "rgba(213, 208, 169, 0.51)",
    alignItems: "center",
  },
  clearButtonText: {
    color: "#803511",
    fontWeight: "500",
  },
  applyButton: {
    flex: 1,
    padding: rem(12),
    borderRadius: rem(16),
    backgroundColor: "#803511",
    alignItems: "center",
  },
  applyButtonText: {
    color: "white",
    fontWeight: "500",
  },
  outgoingRequests: {
    zIndex: 10000,
    position: "absolute",
    top: 230,
    left: 10,
    backgroundColor: "white",
    width: 70,
    height: 70,
    borderRadius: 25,
    justifyContent: "center",
    alignItems: "center",
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    fontFamily: "Poppins-Bold",
    fontWeight: "bold",
    color: "#803511",
  },
  userMarkers: {
    zIndex: 10000,
    position: "absolute",
    top: 310,
    left: 10,
    backgroundColor: "white",
    width: 70,
    height: 70,
    borderRadius: 25,
    justifyContent: "center",
    alignItems: "center",
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    fontFamily: "Poppins-Bold",
    fontWeight: "bold",
    color: "#803511",
  },
  dateInputContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 8,
  },
  dateInput: {
    flex: 1,
    backgroundColor: "#FFFBE4",
    borderRadius: 8,
    padding: 12,
    marginHorizontal: 4,
    borderWidth: 1,
    borderColor: "#803511",
  },
  dateInputText: {
    color: "#803511",
    textAlign: "center",
  },
  locationInputContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 8,
  },
  locationInput: {
    flex: 1,
    backgroundColor: "#FFFBE4",
    borderRadius: 8,
    padding: 12,
    marginHorizontal: 4,
    borderWidth: 1,
    borderColor: "#803511",
    color: "#803511",
  },
  creatorInput: {
    backgroundColor: "#FFFBE4",
    borderRadius: 8,
    padding: 12,
    marginTop: 8,
    borderWidth: 1,
    borderColor: "#803511",
    color: "#803511",
  },
});
