import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  root: {
    flex: 1,
  },
  backgroundImage: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  title: {
    fontSize: 22,
    fontWeight: "700",
    marginBottom: 15,
    color: "#5B3400",
  },
  input: {
    width: "100%",
    backgroundColor: "#fff",
    borderColor: "#AC591A",
    borderWidth: 1,
    borderRadius: 10,
    padding: 12,
    marginBottom: 12,
    fontSize: 16,
  },
  saveButton: {
    backgroundColor: "#AC591A",
    padding: 16,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 10,
    // marginBottom: 30,
    width: "100%",
    alignSelf: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 4,
  },
  saveButtonText: {
    color: "#FFFBE4",
    fontWeight: "700",
    fontSize: 16,
  },
  avatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    marginBottom: 15,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#ddd",
  },
  backButton: {
    padding: 8,
    position: "absolute",
    top: 50,
    left: 10,
    zIndex: 1,
  },
  backButtonText: {
    fontSize: 16,
    color: "#5B3400",
    fontWeight: "bold",
  },
  avatarContainer: {
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 24,
    position: "relative",
    width: 140,
    height: 140,
    alignSelf: "center",
  },
  profileImage: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: "#FFFBE4",
    borderWidth: 3,
    borderColor: "#AC591A",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
  },
  cameraButton: {
    position: "absolute",
    bottom: 10,
    right: 10,
    backgroundColor: "#AC591A",
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#FFFBE4",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 4,
  },
  uploadAvatarButton: {
    backgroundColor: "#FFFBE4",
    borderColor: "#AC591A",
    borderWidth: 1,
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 18,
    alignSelf: "center",
    marginBottom: 18,
  },
  uploadAvatarButtonText: {
    color: "#AC591A",
    fontWeight: "700",
    fontSize: 15,
  },
  form: {
    width: "100%",
    // marginTop: 10,
    // marginBottom: 30,
    gap: 10,
  },
  profileImageTouchable: {
    width: 120,
    height: 120,
    borderRadius: 60,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
  },
});
